version: "3.8"
services:
  mysql:
    image: "mysql:9"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: dinotest
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_ROOT_HOST: '%'

  postgresql:
    image: "postgres:16"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres

  clickhouse:
    image: "clickhouse:lts"
    ports:
      - "9000:9000"
      - "8123:8123"
    restart: always
