name: kotlin
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    if: false
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24.1'
      - name: install ./...
        run: go install ./...
      - uses: actions/checkout@v5
        with:
          repository: sqlc-dev/sqlc-gen-kotlin
          path: kotlin
      - run: make test
        working-directory: kotlin
      - run: sqlc diff
        working-directory: kotlin/examples

