name: docker
on:
  push:
    branches:
      main
jobs:
  docker:
    name: push kjconroy/sqlc:devel
    runs-on: ubuntu-latest
    steps:
    - name: Set created date
      id: prep
      run: |
        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - uses: actions/checkout@v2.4.0
    - uses: docker/setup-buildx-action@v1
    - uses: docker/setup-qemu-action@v1
    - uses: docker/login-action@v1.10.0
      with:
        username: kjconroy
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2.6.1
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        build-args: |
          github_ref=${{ github.ref }}
          github_sha=${{ github.sha }}
        tags: kjconroy/sqlc:devel
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.html_url }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}
        push: true
